name: remote ssh command
on: [push]
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Rebuild bot
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: 22
        script: cd /teaching-server/laurel/discord-bot && docker-compose down && docker-compose pull && docker-compose up -d --build
